### ISSUE TITLE
CT: getLocalToGlobalMatrix unable to work for DAG

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ratio-and-proportion#193]
Failing consistently in CT since 9/28 @ 5:24pm

```
ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1601359213917%22%2C%22timestamp%22%3A1601360520456%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
Error: Assertion failed: getLocalToGlobalMatrix unable to work for DAG
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/assert/js/assert.js:22:13)
at VBox.getLocalToGlobalMatrix (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/scenery/js/nodes/Node.js:4881:17)
at VBox.localToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/scenery/js/nodes/Node.js:4992:37)
at NumberPicker.parentToGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/scenery/js/nodes/Node.js:5041:52)
at NumberPicker.getGlobalBounds (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/scenery/js/nodes/Node.js:5089:17)
at NumberPicker.get globalBounds [as globalBounds] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/scenery/js/nodes/Node.js:5091:36)
at displayFocusListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/scenery/js/listeners/AnimatedPanZoomListener.js:130:52)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/axon/js/TinyEmitter.js:71:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/axon/js/Property.js:277:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601359213917/axon/js/Property.js:175:14)
id: Bayes Chrome
Snapshot from 9/29/2020, 12:00:13 AM
```

**Comment by zepumph** [comment]
Thanks. It looks like the NumberPickers I used in the home screen icons over in https://github.com/phetsims/ratio-and-proportion/issues/84. 

I can remove accessibleContent with this patch:

```diff
Index: js/create/view/CreateScreenIcon.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/create/view/CreateScreenIcon.js	(revision e2d647f17743a3a5b84162598d772f825faca9ee)
+++ js/create/view/CreateScreenIcon.js	(date 1601397957023)
@@ -32,21 +32,25 @@
 
     const tickMarksHiddenProperty = new Property( TickMarkView.NONE );
 
+    const leftNumberPicker = new NumberPicker( new NumberProperty( 1 ), new Property( new Range( 1, 10 ) ) );
+    leftNumberPicker.tagName = null;
     const leftNode = new VBox( {
       align: 'center',
       spacing: 10,
       children: [
         RatioHandNode.createIcon( false, tickMarksHiddenProperty ),
-        new NumberPicker( new NumberProperty( 1 ), new Property( new Range( 1, 10 ) ) )
+        leftNumberPicker
       ]
     } );
 
+    const rightNumberPicker = new NumberPicker( new NumberProperty( 2 ), new Property( new Range( 1, 10 ) ) );
+    rightNumberPicker.tagName = null;
     const rightNode = new VBox( {
       align: 'center',
       spacing: 10,
       children: [
         RatioHandNode.createIcon( true, tickMarksHiddenProperty ),
-        new NumberPicker( new NumberProperty( 2 ), new Property( new Range( 1, 10 ) ) )
+        rightNumberPicker
       ]
     } );
 
```

But I think I would prefer instead to create a static function on NumberPicker to create an icon and always do this. I'll think about it.

**Comment by zepumph** [comment]
I'll clean up CT eagerly, but may change the implementation.

**Comment by zepumph** [comment]
@jessegreenberg and I discussed adding this function to ParallelDOM:

```
      /**
       * Remove this Node from the PDOM display. . . 
       * @public
       */
      removeFromPDOM(){
        this._tagName = null;
      },


```

**Comment by zepumph** [comment]
Added above. Closing
