### ISSUE TITLE
CT position expected to be in valueRange

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#238]
```
ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605476318346%22%2C%22timestamp%22%3A1605477470140%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: position expected to be in valueRange
Error: Assertion failed: position expected to be in valueRange
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/assert/js/assert.js:22:13)
at HandPositionsDescriber.getQualitativePositionIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:170:15)
at HandPositionsDescriber.getQualitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:161:40)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:106:44)
at RatioHandNode.a11yCreateAriaValueText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/RatioHalf.js:133:63)
at RatioHandNode.updateAriaValueText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/sun/js/accessibility/AccessibleValueHandler.js:376:37)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/sun/js/accessibility/AccessibleValueHandler.js:363:16
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Multilink.js:46:20)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/TinyEmitter.js:71:18)
at DynamicProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 11/15/2020, 2:38:38 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605476318346%22%2C%22timestamp%22%3A1605484809408%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/assert/js/assert.js:22:13)
at TickMarkDescriber.getRelativePositionAndTickMarkNumberForPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/TickMarkDescriber.js:130:15)
at HandPositionsDescriber.getQuantitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:139:49)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:112:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/create/view/CreateScreenSummaryNode.js:77:42
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Multilink.js:46:20)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Property.js:280:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Property.js:178:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/DerivedProperty.js:77:19)
id: Bayes Chrome
Snapshot from 11/15/2020, 2:38:38 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605476318346%22%2C%22timestamp%22%3A1605496733288%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: position expected to be in valueRange
Error: Assertion failed: position expected to be in valueRange
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/assert/js/assert.js:22:13)
at HandPositionsDescriber.getQualitativePositionIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:170:15)
at HandPositionsDescriber.getQualitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:161:40)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:106:44)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/create/view/CreateScreenSummaryNode.js:80:42
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Multilink.js:46:20)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Property.js:280:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Property.js:178:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/DerivedProperty.js:77:19)
id: Bayes Chrome
Snapshot from 11/15/2020, 2:38:38 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605476318346%22%2C%22timestamp%22%3A1605509525673%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: position expected to be in valueRange
Error: Assertion failed: position expected to be in valueRange
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/assert/js/assert.js:22:13)
at HandPositionsDescriber.getQualitativePositionIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:170:15)
at HandPositionsDescriber.getQualitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:161:40)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:106:44)
at RatioHandNode.a11yCreateAriaValueText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/RatioHalf.js:133:63)
at RatioHandNode.updateAriaValueText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/sun/js/accessibility/AccessibleValueHandler.js:376:37)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/sun/js/accessibility/AccessibleValueHandler.js:363:16
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Multilink.js:46:20)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/TinyEmitter.js:71:18)
at DynamicProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 11/15/2020, 2:38:38 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605476318346%22%2C%22timestamp%22%3A1605522715637%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: position expected to be in valueRange
Error: Assertion failed: position expected to be in valueRange
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/assert/js/assert.js:22:13)
at HandPositionsDescriber.getQualitativePositionIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:170:15)
at HandPositionsDescriber.getQualitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:161:40)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:106:44)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/discover/view/DiscoverScreenSummaryNode.js:72:44
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Multilink.js:46:20)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Property.js:280:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Property.js:178:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/DerivedProperty.js:77:19)
id: Bayes Chrome
Snapshot from 11/15/2020, 2:38:38 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605476318346%22%2C%22timestamp%22%3A1605534829577%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/assert/js/assert.js:22:13)
at TickMarkDescriber.getRelativePositionAndTickMarkNumberForPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/TickMarkDescriber.js:130:15)
at HandPositionsDescriber.getQuantitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:139:49)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:112:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/ratio-and-proportion/js/discover/view/DiscoverScreenSummaryNode.js:72:44
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Multilink.js:46:20)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/TinyEmitter.js:71:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Property.js:280:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/Property.js:178:14)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605476318346/axon/js/DerivedProperty.js:77:19)
id: Bayes Chrome
Snapshot from 11/15/2020, 2:38:38 PM
```

**Comment by zepumph** [comment]
Thanks. This is from #175

**Comment by zepumph** [comment]
Fixed by https://github.com/phetsims/sun/commit/278bd57e33ca0bf57ed770e8eafb4b5e6a678ee2 and later commits over in https://github.com/phetsims/ratio-and-proportion/issues/175
