### ISSUE TITLE
CT Assertion failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#240]
```
ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605611215948%22%2C%22timestamp%22%3A1605611966747%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/assert/js/assert.js:22:13)
at TickMarkDescriber.getRelativePositionAndTickMarkNumberForPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/ratio-and-proportion/js/common/view/describers/TickMarkDescriber.js:130:15)
at HandPositionsDescriber.getQuantitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:139:49)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:112:19)
at RatioHandNode.a11yCreateAriaValueText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/ratio-and-proportion/js/common/view/RatioHalf.js:133:63)
at RatioHandNode.updateAriaValueText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/sun/js/accessibility/AccessibleValueHandler.js:376:37)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/sun/js/accessibility/AccessibleValueHandler.js:363:16
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/axon/js/Multilink.js:46:20)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/axon/js/TinyEmitter.js:71:18)
at DynamicProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 11/17/2020, 4:06:55 AM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1605611215948%22%2C%22timestamp%22%3A1605618235237%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/assert/js/assert.js:22:13)
at TickMarkDescriber.getRelativePositionAndTickMarkNumberForPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/ratio-and-proportion/js/common/view/describers/TickMarkDescriber.js:130:15)
at HandPositionsDescriber.getQuantitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:139:49)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:112:19)
at RatioHandNode.a11yCreateAriaValueText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/ratio-and-proportion/js/common/view/RatioHalf.js:133:63)
at RatioHandNode.updateAriaValueText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/sun/js/accessibility/AccessibleValueHandler.js:376:37)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/sun/js/accessibility/AccessibleValueHandler.js:363:16
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/axon/js/Multilink.js:46:20)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/axon/js/TinyEmitter.js:71:18)
at DynamicProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1605611215948/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 11/17/2020, 4:06:55 AM
```

**Comment by zepumph** [comment]
Same issue as https://github.com/phetsims/ratio-and-proportion/issues/238. @KatieWoe please ignore CT in this repo until that issue is closed.
