### ISSUE TITLE
CT h is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#359]
```
ratio-and-proportion : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614056535621%7D&fuzzBoard&supportsDescription&memoryLimit=1000
Query: fuzzBoard&supportsDescription&memoryLimit=1000
Uncaught TypeError: h is not a function
TypeError: h is not a function
at dC.a11yMapValue [as _a11yMapValue] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614056535621%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:1053314)
at dC.handleKeyDown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614056535621%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:956870)
at qh.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614056535621%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:503484)
at qh.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614056535621%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:503659)
at qh.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614056535621%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:503165)
at qh.dispatchPDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614056535621%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:499615)
at keydownAction.Pt.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614056535621%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:496378)
at Ct.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614056535621%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:30233)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614056535621%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:497276)
at HTMLInputElement.dispatchEvent (<anonymous>)
id: Bayes Chrome
Snapshot from 2/22/2021, 9:04:36 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000
Query: fuzzBoard&supportsDescription&memoryLimit=1000
Uncaught TypeError: h is not a function
TypeError: h is not a function
at dC.a11yMapValue [as _a11yMapValue] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:1053314)
at dC.handleKeyDown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:956870)
at qh.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:503484)
at qh.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:503659)
at qh.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:503165)
at qh.dispatchPDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:499615)
at keydownAction.Pt.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:496378)
at Ct.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:30233)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:497276)
at Od.triggerDOMEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614076086379%7D&fuzzBoard&supportsDescription&memoryLimit=1000:856:616163)
id: Bayes Chrome
Snapshot from 2/22/2021, 9:04:36 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614057100338%7D&brand=phet&ea&fuzzBoard&supportsDescription&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescription&memoryLimit=1000
Uncaught Error: Assertion failed: transformSourceNode cannot use DAG, must have single trail.
Error: Assertion failed: transformSourceNode cannot use DAG, must have single trail.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/assert/js/assert.js:25:13)
at FocusHighlightFromNode.getUniqueHighlightTrail (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/scenery/js/accessibility/FocusHighlightPath.js:238:15)
at FocusOverlay.activateHighlight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/scenery/js/overlays/FocusOverlay.js:186:39)
at FocusOverlay.onFocusChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/scenery/js/overlays/FocusOverlay.js:423:12)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/axon/js/Property.js:294:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/axon/js/Property.js:191:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/axon/js/Property.js:364:32)
at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/scenery/js/display/Display.js:2108:30)
at Object.focus (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/scenery/js/input/PDOMPointer.js:59:25)
id: Bayes Chrome
Snapshot from 2/22/2021, 9:04:36 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614053076222%22%2C%22timestamp%22%3A1614075421669%7D&brand=phet&ea&fuzzBoard&supportsDescription&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescription&memoryLimit=1000
Uncaught Error: Assertion failed: transformSourceNode cannot use DAG, must have single trail.
Error: Assertion failed: transformSourceNode cannot use DAG, must have single trail.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/assert/js/assert.js:25:13)
at FocusHighlightFromNode.getUniqueHighlightTrail (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/scenery/js/accessibility/FocusHighlightPath.js:238:15)
at FocusOverlay.activateHighlight (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/scenery/js/overlays/FocusOverlay.js:186:39)
at FocusOverlay.onFocusChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/scenery/js/overlays/FocusOverlay.js:423:12)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/axon/js/Property.js:294:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/axon/js/Property.js:191:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/axon/js/Property.js:364:32)
at Function.set focus [as focus] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/scenery/js/display/Display.js:2108:30)
at Object.focus (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614053076222/scenery/js/input/PDOMPointer.js:59:25)
id: Bayes Chrome
Snapshot from 2/22/2021, 9:04:36 PM
```

**Comment by zepumph** [comment]
I forgot to pass an icon to icon creation when I added it to the main object creation. CT should be fixed, but I'll check back soon.

**Comment by zepumph** [comment]
Fixed for the last 5 rows.
