### ISSUE TITLE
CT remainder not in range

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#377]
```
ratio-and-proportion : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1617627252408%22%2C%22timestamp%22%3A1617629403558%7D&brand=phet&ea&fuzz&supportsDescription&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescription&memoryLimit=1000
Uncaught Error: Assertion failed: remainder not in range
Error: Assertion failed: remainder not in range
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/assert/js/assert.js:25:13)
at TickMarkDescriber.getRelativePositionAndTickMarkNumberForPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/TickMarkDescriber.js:92:15)
at HandPositionsDescriber.getQuantitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:109:49)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:98:19)
at BothHandsDescriber.getBothHandsPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/BothHandsDescriber.js:82:55)
at BothHandsDescriber.getBothHandsDynamicDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/BothHandsDescriber.js:67:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/BothHandsPDOMNode.js:229:65
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/Multilink.js:47:20)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/TinyEmitter.js:86:18)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/Property.js:269:23)
id: Bayes Chrome
Snapshot from 4/5/2021, 6:54:12 AM

----------------------------------

ratio-and-proportion : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1617627252408%22%2C%22timestamp%22%3A1617629175300%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: remainder not in range
Error: Assertion failed: remainder not in range
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/assert/js/assert.js:25:13)
at TickMarkDescriber.getRelativePositionAndTickMarkNumberForPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/TickMarkDescriber.js:92:15)
at HandPositionsDescriber.getQuantitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:109:49)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:98:19)
at BothHandsDescriber.getBothHandsPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/BothHandsDescriber.js:81:54)
at BothHandsDescriber.getBothHandsDynamicDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/BothHandsDescriber.js:67:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/BothHandsPDOMNode.js:229:65
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/Multilink.js:47:20)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/Property.js:269:23)
id: Bayes Chrome
Snapshot from 4/5/2021, 6:54:12 AM

----------------------------------

ratio-and-proportion : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1617627252408%22%2C%22timestamp%22%3A1617628871308%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: remainder not in range
Error: Assertion failed: remainder not in range
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/assert/js/assert.js:25:13)
at TickMarkDescriber.getRelativePositionAndTickMarkNumberForPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/TickMarkDescriber.js:92:15)
at HandPositionsDescriber.getQuantitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:109:49)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:98:19)
at BothHandsDescriber.getBothHandsPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/BothHandsDescriber.js:82:55)
at BothHandsDescriber.getBothHandsDynamicDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/BothHandsDescriber.js:67:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/BothHandsPDOMNode.js:229:65
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/Multilink.js:47:20)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/Property.js:269:23)
id: Bayes Chrome
Snapshot from 4/5/2021, 6:54:12 AM

----------------------------------

ratio-and-proportion : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/studio/?sim=ratio-and-proportion&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1617627252408%22%2C%22timestamp%22%3A1617628633971%7D
Uncaught Error: Uncaught Error: Assertion failed: remainder not in range
Error: Assertion failed: remainder not in range
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/assert/js/assert.js:25:13)
at TickMarkDescriber.getRelativePositionAndTickMarkNumberForPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/TickMarkDescriber.js:92:15)
at HandPositionsDescriber.getQuantitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:109:49)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:98:19)
at BothHandsDescriber.getBothHandsPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/BothHandsDescriber.js:82:55)
at BothHandsDescriber.getBothHandsDynamicDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/BothHandsDescriber.js:67:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/BothHandsPDOMNode.js:229:65
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/Multilink.js:47:20)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/Property.js:269:23)
id: Bayes Chrome
Snapshot from 4/5/2021, 6:54:12 AM

----------------------------------

ratio-and-proportion : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1617627252408%22%2C%22timestamp%22%3A1617630645127%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: remainder not in range
Error: Assertion failed: remainder not in range
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/assert/js/assert.js:25:13)
at TickMarkDescriber.getRelativePositionAndTickMarkNumberForPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/TickMarkDescriber.js:92:15)
at HandPositionsDescriber.getQuantitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:109:49)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:98:19)
at BothHandsDescriber.getBothHandsPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/BothHandsDescriber.js:81:54)
at BothHandsDescriber.getBothHandsDynamicDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/describers/BothHandsDescriber.js:67:22)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/ratio-and-proportion/js/common/view/BothHandsPDOMNode.js:229:65
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/Multilink.js:47:20)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/TinyEmitter.js:86:18)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617627252408/axon/js/Property.js:269:23)
id: Bayes Chrome
Snapshot from 4/5/2021, 6:54:12 AM
```

**Comment by zepumph** [comment]
I can't reproduce this after 10 minutes of fuzzing in `fuzz` and `fuzzzBoard`. I'll keep trying.

**Comment by KatieWoe** [comment]
Still occurs:
```
ratio-and-proportion : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1621225698973%22%2C%22timestamp%22%3A1621233452498%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: remainder not in range
Error: Assertion failed: remainder not in range
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/assert/js/assert.js:25:13)
at TickMarkDescriber.getRelativePositionAndTickMarkNumberForPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/ratio-and-proportion/js/common/view/describers/TickMarkDescriber.js:92:15)
at HandPositionsDescriber.getQuantitativeHandPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:109:49)
at HandPositionsDescriber.getHandPositionDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:98:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/ratio-and-proportion/js/create/view/CreateScreenSummaryNode.js:87:42
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/axon/js/Multilink.js:47:20)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/axon/js/TinyEmitter.js:86:18)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/axon/js/Property.js:269:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/axon/js/Property.js:184:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/axon/js/DerivedProperty.js:112:13)
id: Bayes Chrome
Snapshot from 5/16/2021, 10:28:18 PM
```
Reopening

**Comment by zepumph** [comment]
Thanks, I see that too. I'm fuzzing locally now to try to reproduce, it takes many minutes for me.

**Comment by zepumph** [comment]
I'm hopeful that this will fix the error. I'll check back on CT.

**Comment by zepumph** [comment]
I haven't seen this error in quite some time. I'm going to optimistically close this. :)
