### ISSUE TITLE
CT reentry detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#393]
```
ratio-and-proportion : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1631353521152%22%2C%22timestamp%22%3A1631665030584%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=0.965, oldValue=0.69
Error: Assertion failed: reentry detected, value=0.965, oldValue=0.69
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/assert/js/assert.js:25:13)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/axon/js/Property.js:268:15)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/axon/js/TinyEmitter.js:86:9)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/axon/js/Property.js:271:23)
id: Bayes Chrome
Snapshot from 9/11/2021, 3:45:21 AM

----------------------------------

ratio-and-proportion : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631353521152%22%2C%22timestamp%22%3A1631453084758%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Average memory used (1001MB) is above our memoryLimit (1000MB). Current memory: 1088MB.
Error: Average memory used (1001MB) is above our memoryLimit (1000MB). Current memory: 1088MB.
at MemoryMonitor.measure (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/joist/js/MemoryMonitor.js:63:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/joist/js/Sim.js:339:28
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/axon/js/Action.js:227:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/joist/js/Sim.js:1092:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/joist/js/Sim.js:1082:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631353521152/joist/js/Sim.js:1060:12)
id: Bayes Chrome
Snapshot from 9/11/2021, 3:45:21 AM
```

**Comment by zepumph** [comment]
I haven't seen this in ages. I'll reopen if it pops up again, but fuzzing locally can't reproduce. Closing

**Comment by zepumph** [comment]
Still can't reproduce
