### ISSUE TITLE
CT uiScaleFunction is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#408]
```
ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1635881577368%22%2C%22timestamp%22%3A1635883443264%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: uiScaleFunction is not a function
TypeError: uiScaleFunction is not a function
at DiscoverScreenView.RAPScreenView.layoutRAPScreeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/common/view/RAPScreenView.js:296:34)
at new RAPScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/common/view/RAPScreenView.js:316:14)
at new DiscoverScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/discover/view/DiscoverScreenView.js:20:9)
at DiscoverScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/discover/DiscoverScreen.js:26:76)
at DiscoverScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Screen.js:205:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Sim.js:604:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Sim.js:611:29
id: Bayes Chrome
Snapshot from 11/2/2021, 1:32:57 PM

----------------------------------

ratio-and-proportion : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1635881577368%22%2C%22timestamp%22%3A1635883375781%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: uiScaleFunction is not a function
TypeError: uiScaleFunction is not a function
at DiscoverScreenView.RAPScreenView.layoutRAPScreeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/common/view/RAPScreenView.js:296:34)
at new RAPScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/common/view/RAPScreenView.js:316:14)
at new DiscoverScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/discover/view/DiscoverScreenView.js:20:9)
at DiscoverScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/discover/DiscoverScreen.js:26:76)
at DiscoverScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Screen.js:205:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Sim.js:604:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Sim.js:611:29
id: Bayes Chrome
Snapshot from 11/2/2021, 1:32:57 PM

----------------------------------

ratio-and-proportion : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/phet-io-wrappers/phet-io-wrappers-tests.html?sim=ratio-and-proportion&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: ratio-and-proportion: iframe API failed:
Uncaught Error: Uncaught TypeError: uiScaleFunction is not a function
TypeError: uiScaleFunction is not a function
at DiscoverScreenView.RAPScreenView.layoutRAPScreeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/common/view/RAPScreenView.js:296:34)
at new RAPScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/common/view/RAPScreenView.js:316:14)
at new DiscoverScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/discover/view/DiscoverScreenView.js:20:9)
at DiscoverScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/discover/DiscoverScreen.js:26:76)
at DiscoverScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Screen.js:205:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Sim.js:604:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Sim.js:611:29

Uncaught Error: Uncaught TypeError: uiScaleFunction is not a functionTypeError: uiScaleFunction is not a function
at DiscoverScreenView.RAPScreenView.layoutRAPScreeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/common/view/RAPScreenView.js:296:34)
at new RAPScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/common/view/RAPScreenView.js:316:14)
at new DiscoverScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/discover/view/DiscoverScreenView.js:20:9)
at DiscoverScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/ratio-and-proportion/js/discover/DiscoverScreen.js:26:76)
at DiscoverScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Screen.js:205:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Sim.js:604:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1635881577368/chipper/dist/joist/js/Sim.js:611:29
id: Bayes Chrome
Snapshot from 11/2/2021, 1:32:57 PM
```

**Comment by zepumph** [comment]
@samreid, is this from https://github.com/phetsims/dot/issues/112?

**Comment by samreid** [comment]
Yes, probably, I'll take a look.

**Comment by samreid** [comment]
This is similar to what happened in https://github.com/phetsims/gravity-and-orbits/issues/413.  I can see the code is using `evaluate` and not invoking `uiScaleFunction()` directly.  You can see that by navigating to the source file in the stack trace: https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636041297601/chipper/dist/ratio-and-proportion/js/common/view/RAPScreenView.js

I think there is a new caching or stale problem.  I'm not sure where the problem lies.  @jonathanolson or @zepumph can you help me investigate?

**Comment by zepumph** [comment]
Ok, ready for my best guess. . . .

It is because of these lines:

https://github.com/phetsims/aqua/blob/3ef48f258560d90cbb31541705d435fd5f205cda/js/server/ContinuousServer.js#L519-L525

This is the exact same problem as https://github.com/phetsims/phettest/issues/7. 

So we encountered this problem because when you pushed the linearFunction fix, it compiled GAO and RAP before dot was. https://github.com/phetsims/gravity-and-orbits/issues/413 cleaned up because there have been further commits on that repo which CT has pulled, but RAP has not had any more commits. I'm going to test this by committing to RAP now.


It is possible that I'm totally wrong, but if I'm not, then the above commit of some typescript annotations should be enough to recompile. Right? Otherwise I don't know what else to try.

**Comment by samreid** [comment]
I don't have a capture of https://bayes.colorado.edu/continuous-testing/ct-snapshots/1636041297601/chipper/dist/ratio-and-proportion/js/common/view/RAPScreenView.js but it did have the new, correct compiled code in `dist/`.  But it errored as if it had the bad prior code.  So I'm not sure what was going wrong there.  Perhaps we should close this issue or move it to aqua as a sighting?

**Comment by samreid** [comment]
None of the hypotheses identified in this issue can explain the behavior we saw, where it was the new code but acting as if it was the old code.  Also, in https://github.com/phetsims/phettest/issues/7 we made it compile everything after pull all.

**Comment by zepumph** [comment]
You are very correct! Furthermore, I feel confused about when RAP itself stopped displaying this. I wonder if it had to do with a restart I did to CT a couple of days ago? Likely not, as I recall that was closed 8 days ago as part of https://github.com/phetsims/scenery/issues/1318.

**Comment by zepumph** [comment]
Looks like this cleared up also. Like https://github.com/phetsims/gravity-and-orbits/issues/413
