### ISSUE TITLE
CT Assertion failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#430]
```
ratio-and-proportion : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644595960286%22%2C%22timestamp%22%3A1644600018597%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/assert/js/assert.js:25:13)
at HandPositionsDescriber.getSingleHandDistanceProgressSentence (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:181:15)
at HandPositionsDescriber.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:148:33)
at RatioHalf.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/RatioHalf.js:352:35)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/RatioHalf.js:216:33)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/PressListener.js:343:10)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/DragListener.js:214:36)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/axon/js/Action.js:195:18)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/DragListener.js:357:22)
at DragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/PressListener.js:668:14)
id: Bayes Chrome
Snapshot from 2/11/2022, 9:12:40 AM

----------------------------------

ratio-and-proportion : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644595960286%22%2C%22timestamp%22%3A1644597926348%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/assert/js/assert.js:25:13)
at HandPositionsDescriber.getSingleHandDistanceProgressSentence (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:181:15)
at HandPositionsDescriber.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:148:33)
at RatioHalf.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/RatioHalf.js:352:35)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/RatioHalf.js:216:33)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/PressListener.js:343:10)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/DragListener.js:214:36)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/axon/js/Action.js:195:18)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/DragListener.js:357:22)
at DragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/PressListener.js:668:14)
id: Bayes Chrome
Snapshot from 2/11/2022, 9:12:40 AM

----------------------------------

ratio-and-proportion : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644595960286%22%2C%22timestamp%22%3A1644599897825%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/assert/js/assert.js:25:13)
at HandPositionsDescriber.getSingleHandDistanceProgressSentence (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:181:15)
at HandPositionsDescriber.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:148:33)
at RatioHalf.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/RatioHalf.js:352:35)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/RatioHalf.js:216:33)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/PressListener.js:343:10)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/DragListener.js:214:36)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/axon/js/Action.js:195:18)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/DragListener.js:357:22)
at DragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/PressListener.js:668:14)
id: Bayes Chrome
Snapshot from 2/11/2022, 9:12:40 AM

----------------------------------

ratio-and-proportion : voicing-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22voicing-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1644595960286%22%2C%22timestamp%22%3A1644598041045%7D&brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/assert/js/assert.js:25:13)
at HandPositionsDescriber.getSingleHandDistanceProgressSentence (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:181:15)
at HandPositionsDescriber.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:148:33)
at RatioHalf.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/RatioHalf.js:352:35)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/RatioHalf.js:216:33)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/PressListener.js:343:10)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/DragListener.js:214:36)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/axon/js/Action.js:195:18)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/DragListener.js:357:22)
at DragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/PressListener.js:668:14)
id: Bayes Chrome
Snapshot from 2/11/2022, 9:12:40 AM

----------------------------------

ratio-and-proportion : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1644595960286%22%2C%22timestamp%22%3A1644601502654%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/assert/js/assert.js:25:13)
at HandPositionsDescriber.getSingleHandDistanceProgressSentence (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:181:15)
at HandPositionsDescriber.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/describers/HandPositionsDescriber.js:148:33)
at RatioHalf.getSingleHandContextResponse (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/RatioHalf.js:352:35)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/ratio-and-proportion/js/common/view/RatioHalf.js:216:33)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/PressListener.js:343:10)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/DragListener.js:214:36)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/axon/js/Action.js:195:18)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/DragListener.js:357:22)
at DragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1644595960286/chipper/dist/js/scenery/js/listeners/PressListener.js:668:14)
id: Bayes Chrome
Snapshot from 2/11/2022, 9:12:40 AM
```

**Comment by zepumph** [comment]
@terracoda, there is a case where we are dragging the mouse, and then the current distance between the hands is the exact same as the previous distance. It is a bit rare, but can happen when you drag with the mouse to the exact position of the other hand (without letting go and getting the snap-to functionality).


How would you like to handle this case? It is pretty rare, so I would be totally fine with just providing either closer/farther case. Alternatively, if it is in this case. I could provide the distance region.

What do you think?

**Comment by zepumph** [comment]
We will return null if they are equal, and support using distance region again.

**Comment by zepumph** [comment]
In https://github.com/phetsims/ratio-and-proportion/issues/429 we are supporting returning null anyways, so the "distanceProgress-only" function can still return distance region in some cases. Thus, it was pretty simple to add that case here, where now we give distance region when the previous distance is the same as the new distance. Closing
