### ISSUE TITLE
CT cannot read property toLowerCase of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#50]
```
ratio-and-proportion : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:1029417
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:62042)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:76031
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:59160)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:76235)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:510813)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:1030037)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535280)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535479)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589431050451%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535021)
id: Bayes Chrome
Snapshot from 5/13/2020, 9:00:51 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:1029417
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:62042)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:76031
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:59160)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:76235)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:510813)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:1030037)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535280)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535479)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589438661697%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535021)
id: Bayes Chrome
Snapshot from 5/13/2020, 9:00:51 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:1029417
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:62042)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:76031
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:59160)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:76235)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:510813)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:1030037)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535280)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535479)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589452656857%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535021)
id: Bayes Chrome
Snapshot from 5/13/2020, 9:00:51 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:1029417
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:62042)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:76031
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:59160)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:76235)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:510813)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:1030037)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535280)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535479)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/build/phet/ratio-and-proportion_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589464310760%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:4550:535021)
id: Bayes Chrome
Snapshot from 5/13/2020, 9:00:51 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589428416743%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/js/free-objects/view/RatioInteractionListener.js:41:27
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Emitter.js:58:19)
at KeyStateTracker.keydownUpdate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/accessibility/KeyStateTracker.js:84:25)
at RatioInteractionListener.keydown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/js/free-objects/view/RatioInteractionListener.js:82:69)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1829:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1861:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1787:10)
id: Bayes Chrome
Snapshot from 5/13/2020, 9:00:51 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589436839786%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/js/free-objects/view/RatioInteractionListener.js:41:27
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Emitter.js:58:19)
at KeyStateTracker.keydownUpdate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/accessibility/KeyStateTracker.js:84:25)
at RatioInteractionListener.keydown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/js/free-objects/view/RatioInteractionListener.js:82:69)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1829:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1861:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1787:10)
id: Bayes Chrome
Snapshot from 5/13/2020, 9:00:51 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589449231058%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/js/free-objects/view/RatioInteractionListener.js:41:27
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Emitter.js:58:19)
at KeyStateTracker.keydownUpdate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/accessibility/KeyStateTracker.js:84:25)
at RatioInteractionListener.keydown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/js/free-objects/view/RatioInteractionListener.js:82:69)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1829:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1861:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1787:10)
id: Bayes Chrome
Snapshot from 5/13/2020, 9:00:51 PM

----------------------------------

ratio-and-proportion : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589425251158%22%2C%22timestamp%22%3A1589466229843%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
TypeError: Cannot read property 'toLowerCase' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/js/free-objects/view/RatioInteractionListener.js:41:27
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/axon/js/Emitter.js:58:19)
at KeyStateTracker.keydownUpdate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/accessibility/KeyStateTracker.js:84:25)
at RatioInteractionListener.keydown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/ratio-and-proportion/js/free-objects/view/RatioInteractionListener.js:82:69)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1829:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1861:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589425251158/scenery/js/input/Input.js:1787:10)
id: Bayes Chrome
Snapshot from 5/13/2020, 9:00:51 PM
```

**Comment by zepumph** [comment]
Thanks! Keyboard fuzzing isn't supporting the new `key` pattern, and will be worked on further over in https://github.com/phetsims/scenery/issues/1053. The above fixes the error though.
