### ISSUE TITLE
Voicing Assertion with `?audio=disabled`

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#522]
Tagging @jessegreenberg, most likely we will want to figure out how to solve this sooner rather than later.

http://localhost:8080/ratio-and-proportion/ratio-and-proportion_en.html?brand=phet&ea&debugger&voicingInitiallyEnabled&printVoicingResponses&preferencesStorage&fuzz&audio=disabled

```
Uncaught Error: Assertion failed: should have a can speak Property
    at window.assertions.assertFunction (assert.js:28:13)
    at VoicingManager.announce (SpeechSynthesisAnnouncer.ts:465:15)
    at UtteranceQueue.attemptToAnnounce (UtteranceQueue.ts:605:24)
    at UtteranceQueue.announceImmediately (UtteranceQueue.ts:566:14)
    at UtteranceQueue.addToBack (UtteranceQueue.ts:175:12)
    at ExpandCollapseButton.speakContent (Voicing.ts:346:31)
    at ExpandCollapseButton.collectAndSpeakResponse (Voicing.ts:312:12)
    at ExpandCollapseButton.voicingSpeakFullResponse (Voicing.ts:213:12)
    at expandedPropertyObserver (AccordionBox.ts:435:33)
    at BooleanProperty.link (ReadOnlyProperty.ts:407:5)
```

**Comment by jessegreenberg** [comment]
Requires the combination of `audio=disabled&voicingInitiallyEnabled`

**Comment by jessegreenberg** [comment]
This is happening because when audio is disabled PreferencesModel.supportsVoicing is false and so the SpeechSynthesisAnnouncer is never initialized. 

I made it more graceful in the above commit. What do you think about this @zepumph?

**Comment by jessegreenberg** [comment]
Ah very good! I wasn't sure how to best do it but that is nice. I slightly prefer not returning early so I will leave as is but similarly don't feel strongly. Closing.
