### ISSUE TITLE
Assertion failed: (antecedant out of provided range)

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#556]
From https://github.com/phetsims/phet-io/issues/2002.

We are doing some crazy things in this sim to keep ratio, and from the stack trace, it looks like the issue is when you lock the ratio while the antecedent value is at 0.

<details>

```
ratio-and-proportion : phet-io-fuzz : unbuilt
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1734709063776/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1734709063776%22%2C%22timestamp%22%3A1734709965695%7D&ea&brand=phet-io&phetioStandalone&fuzz&phetioLogFuzzedValues
ERROR: QUERY: ea&brand=phet-io&phetioStandalone&fuzz&phetioLogFuzzedValues
Error: Assertion failed
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1734709063776/assert/js/assert.js:45:21
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1734709063776/assert/js/assert.js:45:21)
    at assert (../../../../../../../ratio-and-proportion/js/common/model/RAPRatio.ts:185:14)
    at clampRatioTupleValuesInRange (../../../../../../../ratio-and-proportion/js/common/model/RAPRatio.ts:143:35)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:196:13)
    at emit (../../../../../axon/js/ReadOnlyProperty.ts:344:22)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:288:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:268:11)
    at set (../../../../../axon/js/Property.ts:54:10)
    at  (../../../../../../../ratio-and-proportion/js/common/model/RAPRatio.ts:162:33)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:185:17)
    at emit (../../../../../axon/js/ReadOnlyProperty.ts:344:22)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:288:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:268:11)
    at set (../../../../../axon/js/Property.ts:54:10)
    at  (../../../../../../../ratio-and-proportion/js/common/model/RAPRatio.ts:153:51)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:185:17)
    at emit (../../../../../axon/js/ReadOnlyProperty.ts:344:22)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:288:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:268:11)
    at set (../../../../../axon/js/Property.ts:54:10)
    at  (../../../../../../sun/js/buttons/ToggleButtonModel.ts:72:6)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:196:13)
    at emit (../../../../../axon/js/Emitter.ts:64:21)
    at emit (../../../../../../sun/js/buttons/ToggleButtonModel.ts:88:24)
    at toggle (../../../../../../sun/js/buttons/ToggleButtonModel.ts:56:15)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:185:17)
    at emit (../../../../../axon/js/ReadOnlyProperty.ts:344:22)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:288:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:268:11)
    at set (../../../../../axon/js/Property.ts:65:10)
    at set (../../../../../../sun/js/buttons/ButtonModel.ts:197:24)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:185:17)
    at emit (../../../../../axon/js/ReadOnlyProperty.ts:344:22)
    at _notifyListeners (../../../../../axon/js/ReadOnlyProperty.ts:288:13)
    at unguardedSet (../../../../../axon/js/ReadOnlyProperty.ts:268:11)
    at set (../../../../../axon/js/Property.ts:54:10)
    at  (../../../../../../scenery/js/listeners/PressListener.ts:761:4)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/listeners/PressListener.ts:519:24)
    at release (../../../../../../scenery/js/listeners/PressListener.ts:865:11)
    at inputEvent (../../../../../../scenery/js/input/Input.ts:1875:91)
    at dispatchToListeners (../../../../../../scenery/js/input/Input.ts:1824:9)
    at dispatchEvent (../../../../../../scenery/js/input/Input.ts:1628:9)
    at upEvent (../../../../../../scenery/js/input/Input.ts:395:11)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../../scenery/js/input/Input.ts:1194:23)
    at mouseUp (../../../../../../scenery/js/input/InputFuzzer.js:275:26)
    at mouseToggle (../../../../../../scenery/js/input/InputFuzzer.js:40:11)
    at action (../../../../../../scenery/js/input/InputFuzzer.js:107:6)
    at fuzzEvents (../../../../../joist/js/SimDisplay.ts:221:23)
    at fuzzInputEvents (../../../../../joist/js/Sim.ts:1141:42)
    at fuzzFrame (../../../../../joist/js/Sim.ts:1042:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1036:11)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1734709063776%2Fratio-and-proportion%2Fratio-and-proportion_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz%26phetioLogFuzzedValues&testInfo=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1734709063776%22%2C%22timestamp%22%3A1734709965695%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1734709063776%2Fratio-and-proportion%2Fratio-and-proportion_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz%26phetioLogFuzzedValues&testInfo=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1734709063776%22%2C%22timestamp%22%3A1734709965695%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1734709063776/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1734709063776%22%2C%22timestamp%22%3A1734709965695%7D&ea&brand=phet-io&phetioStandalone&fuzz&phetioLogFuzzedValues
[CONSOLE] enabling assert
[LOADED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1734709063776%2Fratio-and-proportion%2Fratio-and-proportion_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz%26phetioLogFuzzedValues&testInfo=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1734709063776%22%2C%22timestamp%22%3A1734709965695%7D
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1734709063776/chipper/dist/js/tambo/js/phetAudioContext.js" line: 11}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1734709063776/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1734709063776/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1734709063776/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1734709063776/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNoRadioButton.enabledProperty: false
[CONSOLE] continuous-test-load
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.visibleProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.resetAllButton.enabledProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.resetAllButton.enabledProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesTabs.visualTab.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.displayOnlyProperty: true
[CONSOLE] ratioAndProportion.general.model.screens.isUserNavigableProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.consequentNumberPicker.enabledProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.keyboardHelpButton.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.listBox.challenge3Item.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNumberedRadioButton.enabledProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showNumberedRadioButton.enabledProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.listBox.challenge2Item.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.keyboardHelpButton.visibleProperty: true
[CONSOLE] ratioAndProportion.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesTabs.localizationTab.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesTabs.audioTab.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.phetButton.phetMenu.fullScreenMenuItem.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.keyboardHelpButton.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.keyboardHelpButton.visibleProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNoRadioButton.enabledProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNoRadioButton.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNumberedRadioButton.visibleProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.resetAllButton.enabledProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNumberedRadioButton.enabledProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.enabledProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNoRadioButton.enabledProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showNoRadioButton.enabledProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showRadioButton.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.keyboardHelpButton.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesTabs.audioTab.visibleProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.listBox.challenge2Item.visibleProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.displayOnlyProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.visibleProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showRadioButton.enabledProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.keyboardHelpButton.visibleProperty: true
[CONSOLE] ratioAndProportion.general.view.navigationBar.preferencesButton.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.visibleProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNoRadioButton.visibleProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNumberedRadioButton.enabledProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showNumberedRadioButton.visibleProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.ratioLockToggleButton.enabledProperty: true
[CONSOLE] ratioAndProportion.general.view.navigationBar.phetButton.enabledProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.listBox.challenge1Item.visibleProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showRadioButton.enabledProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.listBox.challenge3Item.visibleProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.expandCollapseButton.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.resetAllButton.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.enabledProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.displayOnlyProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.enabledProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.enabledProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.resetAllButton.enabledProperty: true
[CONSOLE] ratioAndProportion.general.view.navigationBar.titleText.visibleProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.ratioLockToggleButton.enabledProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showRadioButton.visibleProperty: true
[CONSOLE] ratioAndProportion.general.view.navigationBar.audioToggleButton.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.phetButton.enabledProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.visibleProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.ratioLockToggleButton.enabledProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showNoRadioButton.enabledProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.ratioLockToggleButton.enabledProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showRadioButton.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.visibleProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.enabledProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showNumberedRadioButton.enabledProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.consequentNumberPicker.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.preferencesButton.visibleProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.consequentNumberPicker.visibleProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showNumberedRadioButton.enabledProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.ratioLockToggleButton.enabledProperty: true
[CONSOLE] Assertion failed
[CONSOLE] Debug info: {
  "seed": 0.7333035264737269,
  "currentScreenName": "CreateScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showNumberedRadioButton.enabledProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.enabledProperty: true
[CONSOLE] Assertion failed:  reentry detected, value=[Range (min:0 max:1)], oldValue=[Range (min:0.01 max:1)]
[CONSOLE] Debug info: {
  "seed": 0.7333035264737269,
  "currentScreenName": "CreateScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "ComboBoxListBox"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=[Range (min:0 max:1)], oldValue=[Range (min:0.01 max:1)]
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.antecedentNumberPicker.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.listBox.challenge2Item.visibleProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.antecedentNumberPicker.enabledProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.phetButton.enabledProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showRadioButton.visibleProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showRadioButton.enabledProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.tickMarkViewRadioButtonGroup.showRadioButton.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.display.supportsPanAndZoomProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.enabledProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.listBox.challenge3Item.visibleProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.ratioLockToggleButton.visibleProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.consequentNumberPicker.enabledProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.visibleProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.enabledProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.displayOnlyProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.listBox.challenge1Item.visibleProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNoRadioButton.visibleProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.visibleProperty: true
[CONSOLE] ratioAndProportion.discoverScreen.view.myChallengeComboBox.listBox.challenge2Item.visibleProperty: true
[CONSOLE] ratioAndProportion.general.view.display.supportsPanAndZoomProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.consequentNumberPicker.enabledProperty: false
[CONSOLE] ratioAndProportion.discoverScreen.view.tickMarkViewRadioButtonGroup.showNoRadioButton.visibleProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.resetAllButton.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesTabs.audioTab.visibleProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.resetAllButton.enabledProperty: false
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.expandCollapseButton.visibleProperty: true
[CONSOLE] ratioAndProportion.createScreen.view.myChallengeAccordionBox.consequentNumberPicker.visibleProperty: false
[CONSOLE] ratioAndProportion.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.preferencesDialog.preferencesTabs.audioTab.visibleProperty: true

id: "Sparky Node Firefox"
Snapshot from 12/20/2024, 8:37:43 AM

**Comment by zepumph** [comment]
We'll see how this goes.

**Comment by zepumph** [comment]
The above didn't work. I'm adding logging now.

**Comment by zepumph** [comment]
I haven't seen this come up in the last few days. Unassigning.
