### ISSUE TITLE
CT assertion failed?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#95]
```
ratio-and-proportion : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/ratio-and-proportion/ratio-and-proportion_en.html?continuousTest=%7B%22test%22%3A%5B%22ratio-and-proportion%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595350442573%22%2C%22timestamp%22%3A1595352425156%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: have not thought through this case, but should soon!
Error: Assertion failed: have not thought through this case, but should soon!
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/assert/js/assert.js:22:13)
at RatioAndProportionModel.adjustFitness (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/ratio-and-proportion/js/common/model/RatioAndProportionModel.js:126:17)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/ratio-and-proportion/js/common/model/RatioAndProportionModel.js:97:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/axon/js/TinyEmitter.js:69:53)
at DynamicProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/axon/js/Property.js:273:25)
at DynamicProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/axon/js/Property.js:171:14)
at DynamicProperty.onPropertyPropertyChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/axon/js/DynamicProperty.js:214:11)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/axon/js/TinyEmitter.js:69:53)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/axon/js/Property.js:273:25)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595350442573/axon/js/Property.js:171:14)
id: Bayes Chrome
Snapshot from 7/21/2020, 10:54:02 AM
```

**Comment by zepumph** [comment]
Now seems like a great time to think this one through! Related to work in #91.

**Comment by zepumph** [comment]
Fixed by reverting code over in https://github.com/phetsims/ratio-and-proportion/issues/91, closing
